id: 23e0309c4edc4213afdf7b6819f0be7d
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_78-The_Questions_of_Gunaratnasankusumita-v2
  language: en-us
  author: ''
  volume: {}
